AWSTemplateFormatVersion: '2010-09-09'
Description: "Resource stack for PSU Web & Mobile CDN"
Resources:
  Bucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      AccessControl: PublicRead
      BucketName: cdn.wdt.pdx.edu
      Tags:
        - Key: Environment
          Value: prod
  # BucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Ref Bucket
  #     PolicyDocument:
  #       Version: "2012-10-17"
  #       Statement:
  #         - Action:
  #             - "s3:GetObject"
  #           Effect: Allow
  #           Principal: "*"
  #           Resource: !GetAtt Bucket.Arn
  Distribution:
    Type: 'AWS::CloudFront::Distribution'
    Properties:
      DistributionConfig:
        Aliases:
          - cdn.wdt.pdx.edu
        DefaultCacheBehavior:
          ForwardedValues:
            QueryString: false
          TargetOriginId: "default"
          ViewerProtocolPolicy: "allow-all"
        DefaultRootObject: "index.html"
        Enabled: true
        IPV6Enabled: true
        Origins:
          - DomainName: cdn.wdt.pdx.edu.s3.amazonaws.com
            Id: "default"
            S3OriginConfig:
              OriginAccessIdentity: ""
        PriceClass:
          PriceClass_100
  DistributionDomainRecord:
    Type: 'AWS::Route53::RecordSet'
    Properties:
      HostedZoneName: wdt.pdx.edu.
      Name: cdn.wdt.pdx.edu
      Type: CNAME
      AliasTarget:
        DNSName: !GetAtt Distribution.DomainName
        EvaluateTargetHealth: false
        HostedZoneId: Z2FDTNDATAQYW2
  Group:
    Type: AWS::IAM::Group
    Properties:
      GroupName: cdn-admins
      ManagedPolicyArns:
        - !Ref GroupPolicy
  GroupPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      Description: "Policy for accessing CDN S3 Bucket"
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Action:
              - 's3:*'
            Effect: Allow
            Resource: !GetAtt Bucket.Arn
