#!/bin/bash
# How to add a new version of OpenLayers
# This README is runnable: `README 4.0.1`

if [ -z ${1+x} ]; then
    echo "Pass version as first arg: README X.Y.Z" 1>&2
    exit 1
else
    XYZ="$1"
fi

echo "Adding OpenLayers ${XYZ}..."

# Download a "dist" release from GitHub into this directory

wget --no-verbose "https://github.com/openlayers/openlayers/releases/download/v${XYZ}/v${XYZ}-dist.zip"

# Unzip that file:

unzip "v${XYZ}-dist.zip"

# You'll end with a directory structure like this:

    # v${XYZ}-dist/
                  # ol-debug.js
                  # ol.css
                  # ol.js

# Move the zip file somewhere outside the repo (or delete it)

rm "v${XYZ}-dist.zip"

# Rename the dist directory

mv "v${XYZ}-dist" "$XYZ"

# Open ${XYZ}/ol.js and change this line:

      # define([], factory);

  # to:

      # define('ol', [], factory);

  # This is to make AMD loading work in production.

sed -i.bak -e "s/define(\[\], factory);/define('ol', [], factory);/" "${XYZ}/ol.js"
diff "${XYZ}/ol.js" "${XYZ}/ol.js.bak"
rm -v "${XYZ}/ol.js.bak"

# Add XYZ directory to git

git add "$XYZ"
git status

# Add new version to libs.yaml
echo "Now add OpenLayers ${XYZ} to libs.yaml"
