#!/bin/bash
# How to add a new version of OpenLayers
# This README is runnable: `XYZ="3.7.0" bash README`

# Download a "dist" release from GitHub into this directory

wget https://github.com/openlayers/ol3/releases/download/v${XYZ}/v${XYZ}-dist.zip

# Unzip that file:

unzip v${XYZ}-dist.zip

# You'll end with a directory structure like this:

    # v${XYZ}-dist/
                  # ol-debug.js
                  # ol.css
                  # ol.js

# Move the zip file somewhere outside the repo (or delete it)

rm v${XYZ}-dist.zip

# Rename the dist directory

mv v${XYZ}-dist ${XYZ}

# Open ${XYZ}/ol.js and change this line:

      # define([], factory);

  # to:

      # define('ol', [], factory);

  # This is to make AMD loading work in production.

# Add new version to libs.yaml
